export default function Home() {
    return (
        <section>
            <p>John Winston Ono Lennon (Liverpool, 9 de outubro de 1940 – Nova Iorque, 8 de dezembro de 1980) foi um cantor, compositor e ativista da paz britânico que fundou os Beatles, a banda de maior sucesso comercial na história da música popular. Sua parceria de composição com o colega de banda Paul McCartney foi uma das mais célebres da história da música. Juntamente com George Harrison e Ringo Starr, o grupo alcançou fama mundial durante a década de 1960. Em 1969, Lennon começou a Plastic Ono Band com sua segunda esposa, Yoko Ono, e continuou a seguir carreira solo após a separação dos Beatles em abril de 1970.</p>
            <p>Nascido em Liverpool, Lennon se interessou pelo gênero skiffle quando adolescente. Em 1956, formou sua primeira banda, The Quarrymen, que culminou na criação dos Beatles em 1960. Inicialmente ele era o líder de fato do grupo, porém foi perdendo gradualmente este posto para McCartney. Lennon se caracterizou por sua natureza rebelde e sagaz em sua música, escrita, desenho, em filmes e entrevistas. No auge de sua fama na década de 1960, ele publicou dois livros: In His Own Write e A Spaniard in the Works, ambos coletâneas de escritos sem sentido e desenhos de rabisco. Começando em 1967 por "All You Need Is Love", suas canções foram adotadas como hinos pelo movimento antiguerra e pela contracultura da época.</p>
            <p>Entre 1968 e 1972, Lennon produziu mais de uma dúzia de gravações com Ono, incluindo uma trilogia de álbuns de vanguarda, seu primeiro álbum solo – John Lennon/Plastic Ono Band – e os sucessos internacionais "Give Peace a Chance", "Instant Karma!", "Imagine" e "Happy Xmas (War Is Over)". Em 1969, liderou uma série de protestos pela paz conhecidos como Bed-Ins for Peace. Após se mudar para Nova Iorque em 1971, seu criticismo à Guerra do Vietnã resultou em uma longa tentativa do governo Richard Nixon de deportá-lo. Em 1975, Lennon se retirou da indústria musical para cuidar de seu segundo filho, Sean, e em 1980 retornou com mais uma colaboração com Ono, o álbum Double Fantasy. Ele foi assassinado em frente à sua casa em Manhattan por Mark Chapman, um fã dos Beatles, três semanas após o lançamento de seu último álbum.</p>
            <p>Como intérprete, compositor ou colaborador, Lennon teve 25 canções número um na parada musical da Billboard Hot 100. Double Fantasy, seu álbum solo mais vendido, venceu o Grammy Award para Álbum do Ano logo após sua morte. Em 1982, o Brit Award para Contribuição Excepcional à Música foi dado a ele postumamente. Em 2002, Lennon foi eleito o oitavo maior britânico de todos os tempos pela BBC. A revista Rolling Stone o elegeu o quinto melhor cantor da história e o incluiu na lista dos cem maiores artistas de todos os tempos. Em 1987, ele foi introduzido no Songwriters Hall of Fame. Lennon ainda foi introduzido no Rock and Roll Hall of Fame duas vezes: como membro dos Beatles em 1988 e como artista solo em 1994.</p>
        </section>
    )
}